name: Node CI

on:
  push:
    branches:
      - master
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install npm dependencies
        run: npm install
        working-directory: ./vue-project
      - name: Run ESLint
        run: npm run lint
        working-directory: ./vue-project
  

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
    - name: Install npm dependencies
      run: npm install
      working-directory: ./vue-project
    - name: Run build task
      run: npm run build --if-present
      working-directory: ./vue-project 
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "vue-project/dist/" 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"